# Generated by Django 3.0.2 on 2020-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=100)),
                ('middle_name', models.CharField(help_text='Enter Middle Name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=100)),
                ('gender', models.CharField(choices=[('n', 'none'), ('m', 'Male'), ('f', 'Female')], default='n', help_text='Choose between Male or Female', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Applicants Details',
            },
        ),
    ]
