# Generated by Django 3.0 on 2020-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(help_text='Enter middle name', max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='Enter last name', max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(help_text='Date of Birth', verbose_name='Date of Birth(DoB)')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('date_registered', models.DateTimeField(verbose_name='Date of Registatration')),
                ('gender', models.CharField(choices=[('n', 'none selected'), ('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('parent1_relation', models.CharField(choices=[('N', 'None Selected'), ('M', 'Mother'), ('F', 'father')], max_length=1, verbose_name='Relation With Parent')),
                ('parent1_name1', models.CharField(max_length=100, verbose_name='Parent First Name')),
                ('parent1_name2', models.CharField(max_length=100, verbose_name='Parent Second Name')),
                ('parent1_IdNo', models.IntegerField(verbose_name='Parent Id No')),
                ('parent2_relation', models.CharField(blank=True, choices=[('N', 'None Selected'), ('M', 'Mother'), ('F', 'father')], max_length=1, verbose_name='Relation With Parent')),
                ('parent2_name1', models.CharField(blank=True, max_length=100, verbose_name='Parent First Name')),
                ('parent2_name2', models.CharField(blank=True, max_length=100, verbose_name='Parent Second Name')),
                ('parent2_IdNo', models.IntegerField(blank=True, verbose_name='Parent Id No')),
            ],
        ),
    ]
