# Generated by Django 3.0.2 on 2020-02-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
