# Generated by Django 3.0 on 2020-02-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='parent2_IdNo',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='parent2_name1',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='parent2_name2',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='parent2_relation',
        ),
    ]
