# Generated by Django 3.0 on 2020-02-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_auto_20200205_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TertiaryApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_ID_Number', models.IntegerField(verbose_name='National ID Number')),
                ('national_ID', models.ImageField(upload_to='media/image', verbose_name='National ID Image')),
                ('institution_type', models.CharField(choices=[('c', 'College'), ('u', 'University'), ('t', 'Technical Institutes')], default='c', max_length=1, verbose_name='Type of Institution')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Name of Institution')),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.Applicants')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcpe_year', models.DateField(verbose_name='Year of KCPE')),
                ('kcpe_marks', models.IntegerField(verbose_name='KCPE Marks')),
                ('school_selected', models.CharField(max_length=200, verbose_name='Name of Secondary School')),
                ('school_type', models.CharField(choices=[('n', 'National School'), ('c', 'County School'), ('s', 'Sub-County School'), ('p', 'Private School')], default='p', max_length=1, verbose_name='Type of School')),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.Applicants')),
            ],
        ),
    ]
