# Generated by Django 3.0 on 2020-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_applicants_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
