# Generated by Django 3.0 on 2020-02-04 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_applicants_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date_joined',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
