# Generated by Django 3.0 on 2020-02-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0005_auto_20200204_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
    ]
